// Generated by CoffeeScript 1.6.2
var Collection, extend, inducedOrdering,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Collection = require('backbone').Collection;

extend = require('underscore').extend;

inducedOrdering = function(collection) {
  var func;

  func = function(model) {
    return collection.indexOf(model);
  };
  func.induced = true;
  return func;
};

exports.FilteredCollection = (function(_super) {
  __extends(FilteredCollection, _super);

  function FilteredCollection(underlying, options) {
    var _this = this;

    if (options == null) {
      options = {};
    }
    this.underlying = underlying;
    this.model = underlying.model;
    this.comparator = options.comparator || inducedOrdering(underlying);
    this.options = extend({}, underlying.options, options);
    FilteredCollection.__super__.constructor.call(this, this.underlying.models.filter(this.options.filter), options);
    this.listenTo(this.underlying, {
      reset: function() {
        return _this.reset(_this.underlying.models.filter(_this.options.filter));
      },
      remove: function(model) {
        if (_this.contains(model)) {
          return _this.remove(model);
        }
      },
      add: function(model) {
        if (_this.options.filter(model)) {
          return _this.add(model);
        }
      },
      change: function(model) {
        if (_this.contains(model)) {
          if (!_this.options.filter(model)) {
            return _this.remove(model);
          }
        } else {
          if (_this.options.filter(model)) {
            return _this.add(model);
          }
        }
      },
      sort: function() {
        if (_this.comparator.induced) {
          return _this.sort();
        }
      }
    });
  }

  return FilteredCollection;

})(Collection);
